{% set name = "pyreports" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyreports-{{ version }}.tar.gz
  sha256: 7d159b76d969c71d87310c8f85db8e611e69fa62f7da0e54b165b87b3044e412

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - ldap3
    - mysql-connector-python
    - nosqlapi
    - psycopg2
    - pymssql
    - python >={{ python_min }}
    - tablib

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyreports

about:
  home: https://github.com/MatteoGuadrini/pyreports
  doc_url: https://matteoguadrini.github.io/pyreports
  summary: pyreports is a python library that allows you to create complex report from various sources
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
