{% set name = "pyreports" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyreports-{{ version }}.tar.gz
  sha256: f91c35b69785fc02a02118feddc92d7a09ac72aadab39a16e854e457ade45929

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ldap3
    - mysql-connector-python
    - nosqlapi
    - psycopg2
    - pymssql
    - python >=3.7
    - tablib

test:
  imports:
    - pyreports

about:
  home: https://github.com/MatteoGuadrini/pyreports
  doc_url: https://matteoguadrini.github.io/pyreports
  summary: pyreports is a python library that allows you to create complex report from various sources
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
